version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64
      - amd64

universal_binaries:
  - replace: true

dockers_v2:
  - images:
      - rvolykh/helloworld-mcp
    tags:
      - "{{.Version}}"
    platform:
      - linux/amd64
      - linux/arm64

dockerhub:
  username: rvolykh
  secret_name: GORELEASER_DOCKERHUB_TOKEN

changelog:
  disable: true

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
